/**
 * X-Plane 12 exterior-model manifest (auto-extracted from the user's local
 * install by the obj8 workflow, 2026-08-13). relPaths are requested verbatim
 * from /xp/aircraft/<relPath>; nothing is copied into the repo.
 */
export interface XpModelEntry { folder: string; objs: string[]; liveries: string[] }
export const XP_MODELS: Record<string, XpModelEntry> = {
  "C172": { folder: "Cessna 172 SP", objs: ["Cessna 172 SP/objects/fuselage.obj", "Cessna 172 SP/objects/fuselage_gear.obj", "Cessna 172 SP/objects/fuselage_prop.obj", "Cessna 172 SP/objects/wings.obj", "Cessna 172 SP/objects/glass_out.obj"], liveries: ["full_white", "old_style", "scratches", "waves", "xplane10"] },
  "B738": { folder: "Boeing 737-800", objs: ["Boeing 737-800/objects/738fuselage.obj", "Boeing 737-800/objects/738wings.obj", "Boeing 737-800/objects/738tailwinglets.obj", "Boeing 737-800/objects/738cfm56L.obj", "Boeing 737-800/objects/738cfm56R.obj", "Boeing 737-800/objects/738maingear.obj", "Boeing 737-800/objects/738nosegear.obj", "Boeing 737-800/objects/738alpha.obj"], liveries: ["Aerolineas Argentinas", "Air China", "Alaska", "China Eastern", "Delta", "KLM", "Qantas", "Ryanair", "Southwest", "Thai Lion", "Xiamen"] },
  "A333": { folder: "Airbus A330-300", objs: ["Airbus A330-300/objects/A330_fuselage_A.obj", "Airbus A330-300/objects/A330_fuselage_B.obj", "Airbus A330-300/objects/A330_fuselage_C.obj", "Airbus A330-300/objects/A330_wings.obj", "Airbus A330-300/objects/A330_tail_gearbay.obj", "Airbus A330-300/objects/A330_trent_700.obj", "Airbus A330-300/objects/A330_main_gear.obj", "Airbus A330-300/objects/A330_nose_gear.obj", "Airbus A330-300/objects/A330_exterior_glass.obj", "Airbus A330-300/objects/A330_pax_windows.obj"], liveries: ["AirAsia", "AirCanada", "CathayPacific", "Laminar House", "Lufthansa D-AIKI", "SwissAir", "VirginAtlantic"] },
  "MD82": { folder: "McDonnell Douglas MD-82", objs: ["McDonnell Douglas MD-82/objects/Fuselage_1.obj", "McDonnell Douglas MD-82/objects/Fuselage_2.obj", "McDonnell Douglas MD-82/objects/wings.obj", "McDonnell Douglas MD-82/objects/Hor_stab.obj", "McDonnell Douglas MD-82/objects/Vert_stab.obj", "McDonnell Douglas MD-82/objects/Engines.obj", "McDonnell Douglas MD-82/objects/gear_main.obj", "McDonnell Douglas MD-82/objects/gear_nose.obj", "McDonnell Douglas MD-82/objects/Gear_doors.obj", "McDonnell Douglas MD-82/objects/Details.obj", "McDonnell Douglas MD-82/objects/blend.obj"], liveries: ["Aeromexico", "Alaska Airlines", "Alitalia", "Delta Airlines", "Iberia", "JAL", "Scandinavian Airlines", "White"] },
  "SR22": { folder: "Cirrus SR22", objs: ["Cirrus SR22/objects/SR22_exterior.obj", "Cirrus SR22/objects/SR22_glass.obj"], liveries: ["Carbon CorsoWhite", "Carbon FrostWhite", "Carbon ZanzibarWhite", "Platinum BajaWhite", "Rhodium Sterling"] },
  "BE58": { folder: "Beechcraft Baron 58", objs: ["Beechcraft Baron 58/objects/B58_fuselage.obj", "Beechcraft Baron 58/objects/B58_wings.obj", "Beechcraft Baron 58/objects/B58_J3YF_propellers.obj", "Beechcraft Baron 58/objects/B58_Glass_out.obj", "Beechcraft Baron 58/objects/B58_lights.obj"], liveries: ["Classic", "White"] },
  "PA18": { folder: "Piper PA-18 Super Cub", objs: ["Piper PA-18 Super Cub/objects/fuselage.obj", "Piper PA-18 Super Cub/objects/wing.obj", "Piper PA-18 Super Cub/objects/prop.obj", "Piper PA-18 Super Cub/objects/glass_out.obj"], liveries: ["Redbull", "blue", "red", "white"] },
  "AS21": { folder: "Schleicher ASK 21", objs: ["Schleicher ASK 21/objects/fuse.obj", "Schleicher ASK 21/objects/wing_L.obj", "Schleicher ASK 21/objects/wing_R.obj", "Schleicher ASK 21/objects/tail_oriz.obj", "Schleicher ASK 21/objects/glass.obj"], liveries: ["orange", "white"] },
  "C750": { folder: "Cessna Citation X", objs: ["Cessna Citation X/objects/fuselage_wing/fuselage.obj", "Cessna Citation X/objects/fuselage_wing/wing_L.obj", "Cessna Citation X/objects/fuselage_wing/wing_R.obj", "Cessna Citation X/objects/engine/engine.obj", "Cessna Citation X/objects/gear/gear.obj", "Cessna Citation X/objects/alpha/alpha.obj"], liveries: ["blue lines", "brown waves", "classic", "plain white"] },
}
